### ISSUE TITLE
version .91 was better than version 1.01

### ISSUE THREAD

**Issue by honis56** [Vocab-Apps/anki-hyper-tts#140]
Missing the HyperTTS bar in browser for quick use of preset1 and preset2.

**Comment by luc-languagetools** [comment]
I understand what you mean, but how did choose between preset1 and preset2 ? Did it depend on deck and note type ? If yes, you can configure the rules such that the right preset is applied each time. Ultimately the goal is for HyperTTS to apply audio automatically. 
Even if you don't want automation, you can still choose between preset1 and preset2 manually, just setup the two rules, and go to the gear button, then click "run" for the one you want. It still just takes 2 clicks.

**Comment by honis56** [comment]
I liked the former menu bar, it was simple and comfortable, easy to understand and I would be greatful to have it back.The new thing is complicated, hard to understand and it doesn't work at all.Please, bring back the old one as a choice i.e. with a different number for installation.Best regardsHolgerAm 12.11.23, 11:17 schrieb Luc ***@***.***>:

   
  I understand what you mean, but how did choose between preset1 and preset2 ? Did it depend on deck and note type ? If yes, you can configure the rules such that the right preset is applied each time. Ultimately the goal is for HyperTTS to apply audio automatically. Even if you don't want automation, you can still choose between preset1 and preset2 manually, just setup the two rules, and go to the gear button, then click "run" for the one you want. It still just takes 2 clicks.

**Comment by luc-languagetools** [comment]
OK but can you describe your use case ? How do you choose between preset1 or preset2 ?

**Comment by luc-vocab** [comment]
feel free to re-open but there is insufficient information currently
