### ISSUE TITLE
preset rules: allow skipping when source field is empty

### ISSUE THREAD

**Issue by luc-vocab** [Vocab-Apps/anki-hyper-tts#143]
Some users may have optional rules which don't need to run when a source field is empty. Provide an option to skip the field if source is empty.
requested by Brett over email.

**Comment by Amosnomor** [comment]
Does the wording of this issue ("source _field_ is empty") preclude this option from applying to advanced templates that return the empty string and/or multi-field templates where all fields being empty?

Just adding some details here that we had talked about in email.  I would like to  be able to have a preset like the following always enabled.  Currently it is generating any error when result is the empty string.

<code>
field_1 = '一'
field_2 = template_fields['MeasureWords']
field_3 = template_fields['Traditional']
result = ""
if field_2:
   result = f'{field_1}{field_2}{field_3}'
</code>

**Comment by Dolphyn5** [comment]
Likewise for text processing rules that result in an empty string. Thanks!

**Comment by luc-vocab** [comment]
Please try HyperTTS 1.13: https://www.vocab.ai/updates/preset-rules-status
