### ISSUE TITLE
HyperTTS mouse-over cursor inconsistent behavior after modifying a card field

### ISSUE THREAD

**Issue by Amosnomor** [Vocab-Apps/anki-hyper-tts#145]
After modifying a field in the browser editor, HyperTTS becomes unavailable (ø shown on mouse-over) in all subsequent notes in that browser session. Killing the browser and relaunching it restores HyperTTS.

To reproduce:

Launch browser on a deck that has HyperTTS configured.
In the card editor modify a field (for example set an empty field to something and then erase it).
Select another card in the editor.

I tried to take screenshots of this, but the captured images don't include the mouse-over information.  Let me know if you can't reproduce this and I make a video.

Anki 23.10 (51a10f09) Python 3.9.15 Qt 5.15.2 PyQt 5.15.5
Platform: Linux-5.15.0-88-generic-x86_64-with-glibc2.31
HyperTTS - Add speech to your flashcards ['111623432', 2023-11-20T06:32, 'None', mod]

**Comment by Amosnomor** [comment]
I have re-titled this issue.  HyperTTS remains functional.  The issue is just that there is some mouse-over cursor weirdness that makes one think that it has been disabled. Although confusing, this is not much of an issue.

GitHub isn't like the mp4 I've created with Kazam on Ubuntu, so instead I am adding a handful of images:

1) Initial browser window.  HyperTTS mouse-over cursor looks normal:
![1](https://github.com/Language-Tools/anki-hyper-tts/assets/6507426/b003e449-218a-4eec-883d-5b6408be2be4)

2) Modifying an arbitrary field (English)
![2](https://github.com/Language-Tools/anki-hyper-tts/assets/6507426/88c039a1-3b5d-4dc8-95a0-6fe9e1af0dcc)

3) Erasing the modification to avoid messing up the field.  This step isn't necessary.  Just doing it to avoid leaving noise in the field.
![3](https://github.com/Language-Tools/anki-hyper-tts/assets/6507426/e9377b46-b63f-4f3a-b775-69c865913782)

4) Switch to another card.  Note that the HyperTTS mouse-over cursor is now showing HyperTTS disabled.  This is what initially confused me and cause me to open the issue.
![4](https://github.com/Language-Tools/anki-hyper-tts/assets/6507426/b17c5d0b-a39c-4dc7-8b30-6949be941788)

5) Regardless of what the cursor is saying, the HyperTTS buttons are still working. 
![5](https://github.com/Language-Tools/anki-hyper-tts/assets/6507426/de937354-ad4d-4593-bc80-df4727a18ec9)

6) After dismissing the HyperTTS pop-up window, it looks like the mouse-over cursor is back to normal.
![6](https://github.com/Language-Tools/anki-hyper-tts/assets/6507426/5543ab12-96e8-40ed-87f2-40301a7d8580)

7) But switching to another card show the bad cursor again.
![7](https://github.com/Language-Tools/anki-hyper-tts/assets/6507426/2c98d00c-115a-4bbe-9a0d-ebc7f942ea2a)

**Comment by luc-languagetools** [comment]
Understood thank you so much for the details. I love detailed bug reports like yours ! First step, let me try to reproduce.

**Comment by Amosnomor** [comment]
I see this issue on Ubuntu 20.04, using QT 5.   I just set up a new system with Ubuntu 22.04 / QT 6 and cannot reproduce it there.

**Comment by Amosnomor** [comment]
I can reproduce this problem on two different Ubuntu 20.04 / QT 5 systems here.  Still anecdotal, but QT 5 vs QT 6 seems interesting.

**Comment by luc-languagetools** [comment]
Just to confirm: it happens on QT5 but not on QT6 ?

**Comment by Amosnomor** [comment]
> Just to confirm: it happens on QT5 but not on QT6 ?

Correct.

**Comment by Amosnomor** [comment]
Just saw a variant of this problem for the first time with QT6.  There was no mouse-over cursor at all over the HyperTTS buttons in the browser card editor pane.  And no effect from clicking on the HyperTTS buttons either.   However, I was only able to reproduce it once, within the same Anki session with a newly spawned browser.  Couldn't reproduce on two further tries in fresh Anki sessions. Will try again next time it pops up.

**Comment by luc-languagetools** [comment]
additional information reported by Jerald over email: it seems that clicking into a field somehow alters the behavior, as if the button is expecting a field to be focused.

**Comment by Amosnomor** [comment]
Using QT6 on Linux with Anki 23.12.1, I am seeing [this again](https://github.com/Language-Tools/anki-hyper-tts/issues/145#issuecomment-1830845550) almost every session.  It is still intermittent and requires modifying another field in the note either before or after running HyperTTS generation.  Let me know how I can help debug this.

**Comment by luc-languagetools** [comment]
I'm not able to reproduce this issue on QT60and Anki 23.12.1. This looks like an Anki behavior, let me try to ask on the Anki forums.

**Comment by Amosnomor** [comment]
I have not seen the issue for quite a while, using QT6 and staying up to date with Anki.  Closing.
