### ISSUE TITLE
Regression: [sound] tag is not added to destination field in version 1.xxx

### ISSUE THREAD

**Issue by tzugen** [Vocab-Apps/anki-hyper-tts#165]
After updating from 0.9 i have the problem that after making new presets, HyperTTS recognizes the fields correctly, and also seems to download the speech snippets, but after it never adds them to the target field, which of course is really necessary.

**Comment by luc-vocab** [comment]
Hi, could you share more details ? Is the processing successful according to the preview screen ?

**Comment by tzugen** [comment]
I have upraded again, and now it works and I cant reprouce the problem anymore.
