### ISSUE TITLE
HyperTTS doesn't do all Rules of Preset rules if there is an error on a Rule / allow generating even when source field empty

### ISSUE THREAD

**Issue by mtthth** [Vocab-Apps/anki-hyper-tts#166]
If a word raises an error (for example, not in Forvo database or from empty field), HyperTTS doesn't goes to the next preset of "Preset rules".

**Comment by luc-vocab** [comment]
also reported by David over email.

**Comment by Amosnomor** [comment]
Hello (David here).  Can this empty field idea be extended allow advanced templates also to optionally return empty (or null?)

**Comment by luc-vocab** [comment]
also reported by Malcom over email

**Comment by Amosnomor** [comment]
Always running everything should work for me. My current use case is that one of my presets, which uses an advanced template, does not know until runtime whether or it wants sound generation done.

Thanks.

**Comment by luc-vocab** [comment]
Please try HyperTTS 1.13: https://www.vocab.ai/updates/preset-rules-status

**Comment by Amosnomor** [comment]
Initial testing look good.  My only comment is wondering if having an explicit don't generate value is generally useful enough. The handling would be to silently quit processing that rule instead of noting it as an error.

Regardless, thanks for the fix/feature.

**Comment by luc-vocab** [comment]
@Amosnomor you mean if the source field is empty, and the preset somehow said "don't complain if the source field is empty, just don't generate", then it wouldn't show an error in red ?

**Comment by luc-vocab** [comment]
going to close this issue, let's open a new one for further improvements.

**Comment by Amosnomor** [comment]
Sorry, I missed your reply.

> @Amosnomor you mean if the source field is empty, and the preset somehow said "don't complain if the source field is empty, just don't generate", then it wouldn't show an error in red ?

Yes.  But now that I've used this for a few days, I am not bothered by the red error message.
