### ISSUE TITLE
Azure service is unavailable, I received an error message

### ISSUE THREAD

**Issue by aimator** [Vocab-Apps/anki-hyper-tts#176]
The error message is:

Encountered an error while Playing Voice Sample: Could not request audio for [campus centre]: Status code: 400 (b'{"error": "Could not generate audio: CancellationReason.Error Connection was closed by the remote host. Error code: 1007. Error details: Starting September 1st, 2021 standard voices will no longer be supported for new users. Please use n USP state: TurnStarted. Received audio size: 0 bytes."}\n') (voice: English (US), Male, Guy (Standard), Azure)

<img width="839" alt="screenshot" src="https://github.com/Vocab-Apps/anki-hyper-tts/assets/16689877/bce192a6-6974-4343-8236-f35458479d58">

How to fix it?

**Comment by luc-vocab** [comment]
Which voice are you trying to use ? can you use an Azure Neural voice instead ?

**Comment by aimator** [comment]
I use "Azure Male, Guy (Standard)" all the time, this is my favorite, i use it on my all cards because it's very clear. I need to keep using it. I really hope you can fix it!

**Comment by luc-vocab** [comment]
Unfortunately Azure is retiring the standard voices, there's not much I can do about it. You can read about it here: https://learn.microsoft.com/en-us/azure/ai-services/speech-service/how-to-migrate-to-prebuilt-neural-voice

**Comment by aimator** [comment]
Thanks for your help. I use an Azure Neural voice instead
