### ISSUE TITLE
Put keyboard focus on "Apply to Notes" in "Add Audio (Collection)" window

### ISSUE THREAD

**Issue by ponychicken** [Vocab-Apps/anki-hyper-tts#177]
When I open the Add Audio window, I should be able to start the process by pressing enter. 
Right now the focus is on the rename preset button, something that i will only very rarely do.

**Comment by luc-vocab** [comment]
OK good point, I assume it should be easy to change this, checking.

**Comment by luc-vocab** [comment]
should be fixed in the next release.
