### ISSUE TITLE
Remove Azure Standard voices

### ISSUE THREAD

**Issue by Amosnomor** [Vocab-Apps/anki-hyper-tts#181]
Following up on #176 there are many Azure Standard voices shown on [](https://www.vocab.ai/languages), particularly among the Chinese voices.  Are these pages generated from services/voicelist.py?  Do these voices need to remain in HyperTTS until Microsoft pulls the plug completely on them?

**Comment by luc-vocab** [comment]
voicelist.py is generated my a script in another repo. I think I need to do something to smooth the transition, the removal of those standard voices is confusing many people. If I simply remove the voices from voicelist.py, people will get an error when they open their presets, so maybe it should start with a warning. Let me think about it a little bit.

**Comment by luc-vocab** [comment]
This is done, standard voices have been removed.
