### ISSUE TITLE
Cannot access local variable 'voice' where it is not associated with a value

### ISSUE THREAD

**Issue by qtdzz** [Vocab-Apps/anki-hyper-tts#182]
## Steps to reproduce
1. Enable the premium Google service (or any premium services which use `basic_voice_list` to get the voice list)
2. Browse a deck
3. Select "Add Audio (Collection)"

![Screenshot_20240601_151744](https://github.com/Vocab-Apps/anki-hyper-tts/assets/11023947/64fab158-34e0-4bd9-b99b-672dc89fd17e)

I am not familiar with Python but it seems the culprit is at https://github.com/Vocab-Apps/anki-hyper-tts/blob/90ffcd692eab9f693899120eb513696240283458/service.py#L74 The  `voice` is not recognized as an imported module in the list comprehension.
Adding a dummy statement before that line to load the module, then it works again
```
        myvoice = voice.Voice('test voice',
                            constants.Gender.Female,
                            languages.AudioLanguage.de_DE,
                            self,
                            'key',
                            'option')
```

It works fine with Free services.

My system:
```
Anki Version ⁨24.04.1 (832d7b16)⁩
Python 3.12.3 Qt 6.7.1 PyQt 6.7.0
HyperTTS v1.10.2
```

**Comment by luc-vocab** [comment]
Are you an Arch linux user ? How did you install Anki ?

**Comment by luc-vocab** [comment]
going to rename the variable to avoid a clash with the module name.

**Comment by qtdzz** [comment]
Thank you for looking into this and sorry for the late reply.

Yes, I am on Arch (Manjaro). I installed using this anki package https://aur.archlinux.org/packages/anki

**Comment by luc-vocab** [comment]
OK. I think I can get into the habit of running regression tests on a python 3.12 venv, this should catch the python 3.12 only issues that Arch users have been facing. As of right now I'm not aware of python 3.12 only issues in HyperTTS that remain.
