### ISSUE TITLE
Please let me scroll in the Preset Rules Window

### ISSUE THREAD

**Issue by jebra102** [Vocab-Apps/anki-hyper-tts#183]
Hey there, first off, I love the Addon. I've been using it since I found it and paid for the Pro version.
Now to the issue at hand:
I have certain notes with all conjugations for my Korean studies. These notes create 32 cards. I'd like to have Sound fields for all of them, which leaves me with a whopping 66 fields in total. So far not an issue, since I can scroll through those. However, I'd need 32 Presets for this specific note type alone. And while I can use my second monitor with a lower zoom, that still hits the limit of what I can see.
So I'd love to be able to scroll in this window. It not being an option makes any changes on these Presets nearly impossible for me.

**Comment by luc-vocab** [comment]
should be fixed in the next release.

**Comment by luc-vocab** [comment]
Please try HyperTTS 1.13.2 which has scrolling in the preset window https://www.vocab.ai/updates/preset-rules-status
