### ISSUE TITLE
Need to save preset every time.

### ISSUE THREAD

**Issue by OdinZhang** [Vocab-Apps/anki-hyper-tts#185]
While I set my preset as advanced template, I need to save my preset every time after I added the sound.

![image](https://github.com/Vocab-Apps/anki-hyper-tts/assets/25601078/a3179925-a3de-4bd6-bca9-6ad54a873854)

**Comment by luc-vocab** [comment]
Can you give me some more details ? What happens when you click save and later try to re-open the preset ?

**Comment by OdinZhang** [comment]
> Can you give me some more details ? What happens when you click save and later try to re-open the preset ?

When I click `HyperTTS->Add Ausio (Collection): {{my template name}}`, it told me to save like this:
![image](https://github.com/user-attachments/assets/3b4c175b-fb30-473b-beaa-95452aad73e8)
after I save it and reopen the template, this will happen again, still need to save it.

**Comment by luc-vocab** [comment]
Sorry i'm not clear. What happens after you open your preset ?

**Comment by OdinZhang** [comment]
> Sorry i'm not clear. What happens after you open your preset ?

![image](https://github.com/user-attachments/assets/4b78e306-1045-4ceb-bf88-4ace020acbf3)
![image](https://github.com/user-attachments/assets/23244f16-8f9d-4299-8bb6-d327dfc34343)

**Comment by luc-vocab** [comment]
Looks like a very simple repro, saving a preset with source=advanced template, then re-opening, shows the save button as enabled without any changes.

**Comment by luc-vocab** [comment]
should be fixed in the next release.
