### ISSUE TITLE
Regex Text Replacement Rules for Realtime TTS don't seem to work.

### ISSUE THREAD

**Issue by jamesesw** [Vocab-Apps/anki-hyper-tts#188]
I tried realtime TTS for my deck and, while it works great for fields that don't need much extra processing, I have a field that consists of a list of definitions, of which I only want audio for the first item. I could easily make it happen when generating audio files by using a regex filter but, when trying to recreate it in realtime TTS, the regex filter did not work for html tags.

Now, I believe that this is because of the option "Run text replacement rules last (uncheck to run first)" doesn't seem to be doing anything.

This is my field
`<div style="text-align: left;" class="yomitan-glossary"><ul><li>trial</li><li>test</li></ul></div>`

and my regex rule
`(?<=/li)(.*)(?=/div)` replaced for an empty space.

This should be outputting "trial" but instead outputs "trial test"

**Comment by luc-vocab** [comment]
if you want text replacement rules to operate on the untransformed HTML, you have to do two things here: https://www.vocab.ai/tutorials/hypertts-collection-audio#text-processing

- uncheck **Process HTML tags**
- uncheck **Run text replacement rules last**

give it a try, let me know if you're stuck, I can help you out (i'll need your deck).

**Comment by jamesesw** [comment]
Yes, I understand what those options do, and like I said, they work properly when creating audio files, but do not provide the same result when creating realtime audio for my cards, even when the same settings are checked and the same filters are provided, as you can see:
![Screenshot_12](https://github.com/user-attachments/assets/406eba32-11e4-4038-920b-cf72663abe7c)
![Screenshot_13](https://github.com/user-attachments/assets/a98231ec-924f-4b5c-868a-21531b66ae8b)

one outputs "trial" as would be expected, the other one outputs "trial test" no matter what settings I check or uncheck.

**Comment by luc-vocab** [comment]
Unfortunately you are right and my reply was completely misguided. When processing realtime audio through the Anki TTS tag, unfortunately the text that makes it way to HyperTTS is already processed (anki strips out html tags). This means the amount of detailed text processing you can do on HyperTTS is limited when it comes to realtime TTS. Would you be able to send me your deck ?
From the Anki main screen, click File → Export, click Export... . Then locate apkg file you just created, and upload it to https://www.dropbox.com/request/X9L4mhPqEcfvKFuSm2nK

**Comment by jamesesw** [comment]
Deck is pretty huge, let me export a smaller sample sized deck for convenience.

**Comment by luc-vocab** [comment]
Hi, I looked at your deck and I apologize I don't have a solution for realtime TTS. The issue is that Anki delivers the text to us already pre-processed when using realtime TTS. Are you open to collection audio ? The text processing capabilites are much more powerful here since we have access to the raw HTML.

**Comment by jamesesw** [comment]
Thanks for taking a look at it, Luc. Yes, I have generated audio files for all the cards, this experiment to use realtime was just to save some space on Media storage as my deck keeps growing. In any case, I can always make a new field to save a simplified version of the English field, and make realtime TTS read that one out instead. But for now I don't mind having the audio files.

**Comment by luc-vocab** [comment]
OK thank you. It's unfortunate that we lose out on lot of capabilities when using realtime TTS but unfortunately that's how Anki works right now.
