### ISSUE TITLE
SentryLogger Error when using ElevenLabsCustom API Key

### ISSUE THREAD

**Issue by yushasama** [Vocab-Apps/anki-hyper-tts#189]
After inputting my Eleven Labs API key for the ElevenLabsCustom module and saving it, I get an error upon attempting to open the HyperTTS menu through Anki's browse section.

"Encountered an unknown error while Launching HyperTTS Batch Dialog from Browser: 'SentryLogger' object has no attribute 'exception'" is the error dialogue received.

**Comment by luc-vocab** [comment]
Thank you for reporting, I need to fix it, but can you tell me which version of HyperTTS you're running ?

**Comment by yushasama** [comment]
I'm on HyperTTS version 0.91, I just reinstalled from the Anki Addon code 111623432.

**Comment by luc-vocab** [comment]
Please upgrade to the latest Anki, I think this bug is fixed in HyperTTS 1.11 or later.

**Comment by yushasama** [comment]
Hello, upgrading to the latest Anki fixed everything. I had assumed Anki automatically updates, thank you Luc!
