### ISSUE TITLE
How to remove a preset that is reporting errors

### ISSUE THREAD

**Issue by 5mdld** [Vocab-Apps/anki-hyper-tts#190]
![image](https://github.com/user-attachments/assets/1b29a59c-352b-41c3-ae8e-3736c5a1f275)

**Comment by luc-vocab** [comment]
Can you try to re-enable the Naver service and then re-open the profile ? In general I may need to add a way to remove profiles without opening them, that doesn't exist right now I believe.

**Comment by 5mdld** [comment]
Thank you, it works.
