### ISSUE TITLE
v1.12.0 Broken Real Time Audio voice_id

### ISSUE THREAD

**Issue by vtruong68** [Vocab-Apps/anki-hyper-tts#194]
Just updated to v1.12.0 and it completely broke realtime audio for me. 

Here's what I get on every card.
![image](https://github.com/user-attachments/assets/c6731309-86ca-45e6-b0a0-049660797bbb)

Trying to edit the realtime audio in the card browser via "Add Audio (Realtime)..." results in the following dialog:
![image](https://github.com/user-attachments/assets/04176c39-3745-42e8-bc98-2fc2abcfb198)

Without saving my changes, I tried removing the audio and redoing it. Attempting to add audio with the "Random" voice setting seems to be where it breaks down.

**Comment by luc-vocab** [comment]
Hi, many apologies for the break, could you try updating to HyperTTS 1.12.1 and see whether this fixes the issue ?

**Comment by vtruong68** [comment]
I tested again on 1.12.2 and it still seems broken. Here's the popup.
![image](https://github.com/user-attachments/assets/ca8340ed-a317-4e98-b86b-02b8da94e08e)

**Comment by luc-vocab** [comment]
I have some bad news. This is due to the a bug I introduced when converting the realtime config to the new format with the 1.12 release. Should be fixed in 1.12.4. Can you re-create your realtime config ? If this is too much work, you can email me your json config and I can fix it for you.

**Comment by tastycroissant** [comment]
v1.12.4 works fine. Thank you

**Comment by vtruong68** [comment]
I'm capable of migrating my config, but thank you!

**Comment by vbomedeiros** [comment]
Hi @luc-vocab , I'm having the same problem. Can I email my config to you? Also, how can I find your email address?

**Comment by luc-vocab** [comment]
if anyone else hits this issue please email hypertts@airpost.net
