### ISSUE TITLE
Hypertts no longer working after update

### ISSUE THREAD

**Issue by Aitprince** [Vocab-Apps/anki-hyper-tts#195]
Encountered an unknown error while Launching HyperTTS Realtime Dialog from Browser: 'Voice' object has no attribute 'audio_languages'. 
Hypertts is down!

**Comment by tastycroissant** [comment]
I have the same error.

**Comment by dougienisbet** [comment]
Same here. Deleting and reverting to old version works fine.

**Comment by luc-vocab** [comment]
many apologies for the issue, could you try updating to HyperTTS 1.12.2 and see whether it fixes the problem ?

**Comment by vbomedeiros** [comment]
I am on 1.12.5 and still see this problem.

**Comment by luc-vocab** [comment]
should be fixed in 1.12.X
