### ISSUE TITLE
This voice currently does not support SSML input. Please try again with text only input. 

### ISSUE THREAD

**Issue by alehpwind** [Vocab-Apps/anki-hyper-tts#200]
Is it possible to support text input? 
When I try to use the following settings, it shows an error. 
While I can choose another model which supports SSML, I was just wondering if it is possible to support text input.
Thanks!

<img width="787" alt="image" src="https://github.com/user-attachments/assets/19ac8e7e-28ff-4192-bf05-8f722363640e">

**Comment by luc-vocab** [comment]
What's the input that you are giving it ?

**Comment by luc-vocab** [comment]
please re-open after providing missing information
