### ISSUE TITLE
Elevenlabs: Missing model Eleven Turbo v2.5

### ISSUE THREAD

**Issue by fvclaus** [Vocab-Apps/anki-hyper-tts#201]
As far as I can see, this model can currently not be selected for any language. It costs 50% less to generate speech so it might be interesting to users of Elevenlabs.

**Comment by luc-vocab** [comment]
Which version of HyperTTS are you on ? 1.12 or later should have the Turbo v2.5 voices.

**Comment by fvclaus** [comment]
Thanks for the quick response. I was in fact on 0.91 but didn't receive any update notifications, because my Anki version was too old.
