### ISSUE TITLE
Advanced template preset code lost when renaming

### ISSUE THREAD

**Issue by Amosnomor** [Vocab-Apps/anki-hyper-tts#204]
Renaming a preset using an advanced template, clobbers the custom code upon saving.  Seen now in v1.13.2, but this may not be a new regression.  I've had problems with this in the past, which I'd previously blamed on myself.

Reproduces reliably in my environment.  I have a deck with two rules enabled. One  is a simple generate sound based upon a fixed field. The second is an advanced template. To reproduce:

From the browser, open up HyperTTS configuration by clicking the gear icon.
Click edit on the advanced template rule.
Click rename at the top of the screen
Enter a new name
Click OK
Click save and close.
At this point meta.json has been updated with the new name, but without the original custom rule code.

Here is the difference in the presets section of the configuration
```
fuyu:-> diff presets.before presets.after
4c4
<         "name": "MeasureWords",
---
>         "name": "MW",
6a7,8
>           "source_field": null,
>           "source_template": "",
8c10
<           "source_template": "conversion = ''\nnoun = template_fields['Traditional']\n# MeasureWords contains mandarin/pinyin[,mandarin/pinyin[...]]\nmeasure_words = template_fields['MeasureWords']\n\nfor mw_pair in measure_words.split(','):\n    mandarin, pinyin = mw_pair.split('/')\n\n    if not (not conversion) :\n        conversion += ' <break time=\"800ms\"/> '\n\n    conversion += '一' + mandarin + noun + '.'\n\nresult = f'{conversion}'\n"
---
>           "use_selection": false
922a925
> 
```
Anki debug info:
```
Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Linux-6.8.0-45-generic-x86_64-with-glibc2.35

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Advanced Browser ['874215009', 2023-10-21T07:34, 'None', '']
HyperTTS - Add speech to your flashcards ['111623432', 2024-09-22T04:17, 'None', mod]
Review Heatmap ['1771074083', 2022-06-29T18:43, 'None', '']

===IDs of active AnkiWeb add-ons===
111623432 1771074083 874215009

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
```

**Comment by luc-vocab** [comment]
Thank you for the detailed report, let me take a look

**Comment by luc-vocab** [comment]
I can reproduce this, working on a fix

**Comment by luc-vocab** [comment]
@Amosnomor please try HyperTTS 1.13.6, I expect the issue should be fixed.

**Comment by Amosnomor** [comment]
Yes.  Initial testing shows this to be fixed.  Thank you.

**Comment by luc-vocab** [comment]
Thank you and I really appreciate your detailed bug reports, they are of great help.
