### ISSUE TITLE
Feature request: add audio from the card editor

### ISSUE THREAD

**Issue by Expertium** [Vocab-Apps/anki-hyper-tts#210]
![image](https://github.com/user-attachments/assets/aa537300-f189-4732-9dcc-58655d7901cb)
This is a feature of the [Simple Forvo Audio](https://github.com/Rascalov/Anki-Simple-Forvo-Audio) add-on. I assume it would be fairly straightforward to do this using HyperTTS, too.

**Comment by luc-vocab** [comment]
This is already possible, see here https://youtu.be/9ywLrzrfpPg?t=62

**Comment by Expertium** [comment]
Ok, thank you. My bad.
