### ISSUE TITLE
Could you add support for adding OpenAI API domains? Thank you very much.

### ISSUE THREAD

**Issue by RichardMadden** [Vocab-Apps/anki-hyper-tts#211]
Could you add support for adding OpenAI API domains? Thank you very much.

**Comment by luc-vocab** [comment]
Can you tell me more about those API domains ?

**Comment by RichardMadden** [comment]
<img width="572" alt="image" src="https://github.com/user-attachments/assets/33026d51-7f64-4719-8c67-38392c2f248b">
Custom API Host

**Comment by luc-vocab** [comment]
Can you tell me more about what you're trying to do ? Does OpenAI provide alternate API hosts ? Or you are trying to access some kind of self-hosted service ?

**Comment by RichardMadden** [comment]
Yes, I would like to use other hosting services.

**Comment by luc-vocab** [comment]
OK, can you tell me which ones ? I need more information to properly test such a change

**Comment by RichardMadden** [comment]
You mean I need to provide the host address? If not, please let me know.
https://api.wlai.vip/
https://api.wlai.vip/v1
https://api.wlai.vip/v1/chat/completions

**Comment by luc-vocab** [comment]
Does this site support the text to speech API ? You won't be able to use the chat completions API in HyperTTS

**Comment by RichardMadden** [comment]
Yes, supported.

**Comment by luc-vocab** [comment]
OK, would you be OK to lend an API key for testing ? you can email me privately hypertts@airpost.net

**Comment by RichardMadden** [comment]
ok

**Comment by RichardMadden** [comment]
I sent it to you, did you receive the email?

**Comment by luc-vocab** [comment]
There's little demand for this unfortunately, I recommend hacking the solution locally , ChatGPT can help you write the code.
