### ISSUE TITLE
Advanced templates aren't loaded properly

### ISSUE THREAD

**Issue by frifix** [Vocab-Apps/anki-hyper-tts#213]
Hi,

I have flash cards like this:
Front: `I don't usualy eat [[ podwieczorek ]]`
Back: `afternoon tea`
<img width="386" alt="ANKI_1" src="https://github.com/user-attachments/assets/492ed73c-7bf3-46cd-be48-caefc7ead564">

I have created an advanced template in HyperTTS that replace the word in [[  ]] brackets with the word that is on the back. Here it's my advanced template script:
```
def format_text(raw, use):
    first = True
    while True:
        start = raw.find('[')
        end = raw.find(']')
        if start == -1 or end == -1:
            break
        if first:
            raw = raw[:start] + use + raw[end+1:]
            first = False
        else:
            raw = raw[:start] + raw[end+1:]
    return raw

front = template_fields['Przód']
back = template_fields['Tył']
result = format_text(front, back)
```

For some reason when I want to add a sound it doesn't work properly for the first time, it shows an error:
<img width="654" alt="ANKI_2" src="https://github.com/user-attachments/assets/a6c63de5-faf8-48b4-8c3b-0318ce83e745">

When I click "Show Settings" and click on "Note Id" it says:
`Error: No "result" variable found. You must assign the final template output to a result variable.`
<img width="902" alt="ANKI_3" src="https://github.com/user-attachments/assets/43700443-f072-426c-a7f1-62913e1d9701">

When I change something in the script (e.g. remove one letter and add it again) then the whole script will be loaded again and the error no longer appears:
<img width="902" alt="ANKI_4" src="https://github.com/user-attachments/assets/101dbe22-20c8-4f87-ac6a-5193049238e0">

It is very annoying that I have to do this every time when I want to add sounds for my flash cards. It would be great if this problem could be solved.

**Comment by luc-vocab** [comment]
looks there's a problem when initializing after loading an advanced template preset
could be related to #204 ?

**Comment by JSchoreels** [comment]
> looks there's a problem when initializing after loading an advanced template preset could be related to #204 ?

Not sure because in my case, I have the same bug but the source_template is still there in the configuration :


      ```
  "ccd5c15f-5d66-44e8-b1ef-a0dfcd0c42ce": {
            "name": "Reading Audio Yomitan",
            "source": {
                "mode": "advanced_template",
                "source_field": null,
                "source_template": "front = template_fields['Front']\nif front:\n  result = front\nelse:\n  result = template_fields['Reading']",
                "template_format_version": "v1",
                "use_selection": false
            },
            "target": {
                "remove_sound_tag": true,
                "target_field": "Audio",
                "text_and_sound_tag": false
            },
            "text_processing": {
                "html_to_text_line": true,
                "ignore_case": false,
                "run_replace_rules_after": true,
                "ssml_convert_characters": true,
                "strip_brackets": false,
                "text_replacement_rules": [
                    {
                        "rule_type": "Simple",
                        "source": "(",
                        "target": ""
                    },
                    {
                        "rule_type": "Simple",
                        "source": ")",
                        "target": ""
                    }
                ]
            },
```

**Comment by luc-vocab** [comment]
@JSchoreels could you let me know whether this still happens with HyperTTS 1.13.6 ?

**Comment by JSchoreels** [comment]
Seems OK now ! Checked with 1.13.5 was KO and then 1.13.6  it's OK

**Comment by frifix** [comment]
It works for me too, thanks for fixing it.
