### ISSUE TITLE
Source Configuration "no result" when preset opened 

### ISSUE THREAD

**Issue by JSchoreels** [Vocab-Apps/anki-hyper-tts#215]
Hello,

I have a preset I updated to have some python rules to select one field and if empty, it goes to the next one 
![image](https://github.com/user-attachments/assets/6e298042-5699-4dac-bd3e-4c8e450c65cc)

![image](https://github.com/user-attachments/assets/53f5864f-fee3-4c81-a263-4fb66323b7ca)

![image](https://github.com/user-attachments/assets/f1fdb0ca-ab8f-4099-8f67-278def747091)

But as you can see, all lines are marked with "Error" saying that it does not find any result set.

If, I take my cursor in the script box and add any char, for ex a newline at the end, the script then work fine and the field appears :

![image](https://github.com/user-attachments/assets/8e60685a-64ea-453e-b231-e11deb7cf641)

I think there is some issue loading initially the saved script, and only by typing something it refreshes correctly

**Comment by luc-vocab** [comment]
I think it may be the same as #213
I'll need to take a look to  fix it.

**Comment by luc-vocab** [comment]
Can you let me know whether this is still happening on HyperTTS 1.13.6 ?

**Comment by JSchoreels** [comment]
Yes now everything is OK ! Closing it, thank you

**Comment by luc-vocab** [comment]
Thank you, if you feel satisfied please leave a review here: https://ankiweb.net/shared/info/111623432
really appreciated !
