### ISSUE TITLE
got status code_403 from https://papago.navar.com/

### ISSUE THREAD

**Issue by seanmcd33** [Vocab-Apps/anki-hyper-tts#217]
This add-on stopped working for me today.  When I request audio I get the following message 

Preset 1: error could not request audio for [my anki sentence] :got status code_403 from https://papago.navar.com/

**Comment by alexaandru** [comment]
Same here: 
![image](https://github.com/user-attachments/assets/06ee721c-6df0-4cb9-835f-d8677cb2f885)

**Comment by seanmcd33** [comment]
This issue is fixed following the latest update.  Thank you!

**Comment by alexaandru** [comment]
Yup, it's back working. Thank you so much for the super quick fix!! :rocket: :tada:

**Comment by luc-vocab** [comment]
Thank you, please remember to leave a review if you are satisfied: https://ankiweb.net/shared/info/111623432
